Se 2929 (#19)
* SE-2929: Added first stab at using redis - keys are stored, but 'something' goes wrong in agency. Debugging tomorrow

* SE-2929: Added client for accessing the redis cache. script/server may need to shut down the cache

* SE-2929: Added first stab at using redis - keys are stored, but 'something' goes wrong in agency. Debugging tomorrow

* SE-2929: Added client for accessing the redis cache. script/server may need to shut down the cache

* SE-2929: Added first stab at using redis - keys are stored, but 'something' goes wrong in agency. Debugging tomorrow

* SE-2929: Added client for accessing the redis cache. script/server may need to shut down the cache

* SE-2929: Newest version is php7.3

* SE-2929: Stop redis when server script stops

* SE-2929: First stab at supporting information from the redis cache. Need to make a checkpoint commit

* SE-2929: Full support for Redis info output in show cache page

* SE-2929: Renamed file to reflect that not only memcache is supported

* SE-2929: Added first stab at using redis - keys are stored, but 'something' goes wrong in agency. Debugging tomorrow

* SE-2929: Added client for accessing the redis cache. script/server may need to shut down the cache

* SE-2929: Newest version is php7.3

* SE-2929: Stop redis when server script stops

* SE-2929: First stab at supporting information from the redis cache. Need to make a checkpoint commit

* SE-2929: Full support for Redis info output in show cache page

* SE-2929: Renamed file to reflect that not only memcache is supported

* SE-2929: Make test script work, sort of. Checking in, to be able to rebase on master

* SE-2929: Added more debug output, and exception handling

* SE-2929: Use arguments to specify other server to test, and request directory

* SE-2929: Added support to test semiautomatically against a golden master

* SE-2929: Output actual strings on error

* SE-2929: Fix minor bug, track time for requests against each url

* SE-2929: Support ability to configure if redis or memcache should be used. Defaults to memcached, if not configured.

* SE-2929: Fixed typos and comments from review

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -5,4 +5,17 @@
 which dirname &> /dev/null || die "Unable to run dirname command - please install it"
 export SCRIPTNAME="test"
 export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
-exec ${SCRIPT_DIR}/../run-system-test.sh "$@"
+. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }
+
+set -e
+
+# We need an argument
+URL_GOLDEN="$1"
+REQ_DIR=${2:-${SCRIPT_DIR}/../tests/requests}
+
+test -z "${URL_GOLDEN}" && die "Usage: $0 <golden_url> [request_dir]"
+
+# Get information about the exposed port of the service from the compose file.
+port=$(get_compose_service_port ${PROJECT_DIR}/docker/docker-compose.yml opensearch-webservice 80)
+URL="http://localhost:${port}/5.2/"
+exec ${SCRIPT_DIR}/../tests/compare_request_results.py ${URL_GOLDEN} ${URL} ${REQ_DIR}
